pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh "./build_full.sh"
            }
        }
    }
    post {
            always{
                xunit(
                  [CTest(deleteOutputFiles: true,
                        failIfNotNew: true,
                        pattern: 'build/Testing/**/Test.xml',
                        skipNoTestFiles: false,
                        stopProcessingIfError: true)]
                     )
        }
    }
}
