pipeline {
    agent any
    stages {
        whitEnv(['BUILD_DISPLAY_NAME=jenkins-${JOB_NAME}-${BUILD_NUMBER}'])

        stage('pre_build')
        {
            steps {
                // dealing with permission denied error for accessing the socket
                sh 'sudo chmod 777 /var/run/docker.sock'
            }
        }
        stage('build') {
            steps {
                sh "./build_full.sh"
            }
        }
    }
    post {
            success{
                xunit(
                  [CTest(deleteOutputFiles: true,
                        failIfNotNew: true,
                        pattern: 'build/Testing/**/Test.xml',
                        skipNoTestFiles: false,
                        stopProcessingIfError: true)]
                     )
        }
    }
}
