pipeline {
    agent any
    stages {
        stage('pre_build')
        {
            steps {
                // dealing with permission denied error for accessing the socket
                sh 'sudo chmod 777 /var/run/docker.sock'
            }
        }
        stage('build') {
            environment {
                 BUILD_DISPLAY_NAME='Build No.:-${BUILD_NUMBER}'
                 JOB_NAME='CI-with-jenkins-and-docker-for-cpp'
            }
            steps {
                sh "./build_full.sh"
            }
        }
    }
    post {
            success {
                xunit(
                  [CTest(deleteOutputFiles: true,
                        failIfNotNew: true,
                        pattern: 'build/Testing/**/Test.xml',
                        skipNoTestFiles: false,
                        stopProcessingIfError: true)]
                     )
            }
            always {
              cleanWs()
            }
    }
}
